### ISSUE TITLE
DTDA integration test failure

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/bioagents#54]
```
======================================================================
FAIL: run_test (tests.dtda_test.TestFindDrugTargets1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sorgerlab/bioagents/tests/integration.py", line 104, in run_test
    assert self.is_correct_response(), self.give_feedback()
  File "/home/travis/build/sorgerlab/bioagents/tests/dtda_test.py", line 96, in is_correct_response
    assert len(self.output.get('targets')) == 1, self.output
AssertionError: (SUCCESS :targets ())
```

**Comment by bgyori** [comment]
Fixed in bd0a27b
